name: Hello world
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Step
        run: Build Step
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Phase
        run: echo "Zrzunning test case"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the app
        run: echo "Deploy the application"
        
      
          
  
        
